In [1]:
# Based on article https://dashee87.github.io/deep%20learning/python/predicting-cryptocurrency-prices-with-deep-learning/

import pandas as pd
import time
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
import numpy as np

In [2]:
# Get Bitcoin data

# get market info for bitcoin from the start of 2013 to the current day
bitcoin_market_info = pd.read_html("https://coinmarketcap.com/currencies/bitcoin/historical-data/?start=20130428&end="+time.strftime("%Y%m%d"))[0]
# convert the date string to the correct date format
bitcoin_market_info = bitcoin_market_info.assign(Date=pd.to_datetime(bitcoin_market_info['Date']))
# when Volume is equal to '-' convert it to 0
bitcoin_market_info.loc[bitcoin_market_info['Volume']=="-",'Volume']=0
# convert to int
bitcoin_market_info['Volume'] = bitcoin_market_info['Volume'].astype('int64')
# look at the first few rows
bitcoin_market_info.head()

        Date    Open*     High      Low  Close**      Volume    Market Cap
0 2018-07-17  6739.65  7387.24  6684.17  7321.04  5961950000  115602000000
1 2018-07-16  6357.01  6741.75  6357.01  6741.75  4725800000  109029000000
2 2018-07-15  6272.70  6403.46  6256.51  6359.64  3285460000  107573000000
3 2018-07-14  6247.50  6298.19  6212.22  6276.12  2923670000  107130000000
4 2018-07-13  6235.03  6310.55  6192.24  6238.05  3805400000  106906000000

In [5]:
# Get Ethereum data

# get market info for ethereum from the start of 2013 to the current day
ethereum_market_info = pd.read_html("https://coinmarketcap.com/currencies/ethereum/historical-data/?start=20130428&end="+time.strftime("%Y%m%d"))[0]
# convert the date string to the correct date format
ethereum_market_info = ethereum_market_info.assign(Date=pd.to_datetime(ethereum_market_info['Date']))
# when Volume is equal to '-' convert it to 0
# ethereum_market_info.loc[ethereum_market_info['Volume']=="-",'Volume']=0
# convert to int
ethereum_market_info['Volume'] = ethereum_market_info['Volume'].astype('int64')
# look at the first few rows
ethereum_market_info.head()

        Date   Open*    High     Low  Close**      Volume   Market Cap
0 2018-07-17  480.08  508.78  468.92   501.00  2288100000  48360500000
1 2018-07-16  450.43  480.66  446.80   480.66  1858680000  45364300000
2 2018-07-15  435.88  454.00  433.92   449.85  1350160000  43890800000
3 2018-07-14  434.51  439.43  431.47   436.09  1235820000  43743700000
4 2018-07-13  430.74  442.36  430.74   434.03  1489670000  43355400000